---
title: "HW 1"
subtitle: "Data 180, Professor Kennedy"
author: 
  name: "Bremar Brown"
  email: "Brownbre@dickinson.edu"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document
---
Make sure that you have accepted the hw invitation link, and working with your clone repository.

**Due date:** September 21 beginning of class.

**Reminder:** You can insert R code in your Rmd file as a chunk in the following way:
```{r}
# Your code goes here
```
Make sure to insert a chunk for each (sub)section of the assignment.

## Preliminary Task
Go to [datacamp.com](https://datacamp.com) and complete the tutorial "Introduction to R".

library(dplyr)

## Task 1
a) Store the data below in a data frame object named `my_df`.


|Person | Preference|
|:------|:----------|
|Alice | Twitter |
| Bob | Facebook |
| Charlie | Twitter |
| Denise | Instagram |
| Erin | Facebook |
| Frank | Twitter |
| Gisele | Twitter |
| Harry | Instagram |

my_df <- data.frame(Person = c( "Alice", "Bob","Charlie","Denise","Erin","Frank","Gisele","Harry"),Preference = c("Twitter","Facebook","Twitter","Instagram","Facebook","Twitter","Twitter","Instagram"))

my_df

b) What are the dimensions of `my_df`?

dim(my_df)

c) Write R code that counts the total number of users.

length(my_df$Person)

d) Write R code that counts the total number of users who prefer Twitter.

total_pref <-filter(my_df, Preference=="Twitter")
length(total_pref$Person)

e) Write R code that returns what Gisele prefers.

filter(my_df, Person=="Gisele")


## Task 2
a) Create a vector named `my_vec` that includes all integers from 1 to 10 (inclusive).

my_vec <-c(1,2,3,4,5,6,7,8,9,10)
my_vec

b) Replace the second element in `my_vec` with the number `99`.

my_vec[2] <- 99
my_vec

c) Write a function called `my_func` that prints `This element is greater than 5!` if an element in `myvec` is greater than 5, and `This element is NOT greater than 5!` otherwise.

my_func <- ifelse(my_vec[1: 10] > 5, "This element is greater than 5!", "This element is NOT greater than 5!")
my_func

## Task 3
a. Write a function named `get_fibonacci` that returns the n'th value in the [fibonacci sequence](https://www.mathsisfun.com/numbers/fibonacci-sequence.html). For example, `get_fibonacci(5)` should return 3; `get_fibonacci(7)` should return 8 and so on. ***Hint:** It is possible to call the same function from inside it. E.g., you can call `get_fibonacci()` from inside `get_fibonacci()`. Like inception!*

get_fibonacci <- function(n) {
  if (n <= 0) {
    stop("Input must be a positive integer.")
  }
  
  if (n == 1) {
    return(0)
  } else if (n == 2) {
    return(1)
  } else {
    a <- 0
    b <- 1
    for (i in 3:n) {
      next_value <- a + b
      a <- b
      b <- next_value
    }
    return(b)
  }
}




b. Using your function in part (a), find and return the 19th value in the fibonacci sequence.

n <- 19
result <- get_fibonacci(n)
result

<br>
You are done! 🏁 Don't forget to `commit` and `push` your .Rmd file to your Github clone repository before the due date.
<br>

